apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: kapatsyndianadockerid/customerservice
          name: customers
          ports:
            - containerPort: 8086
              name: customers
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.1.2:5435/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"